---
name: Hello
on:
  push:
    branches:
      - main
jobs:
  Greet:
    runs-on: ubuntu-letest
    steps:
      - name: Say hello to user
        run: echo "Hello Dosto"
      - name: say hello to username
        run: echo "Hello $USER"
details:
  runs-on: ubuntu-letest
  steps:
    - name: show version of python,docker
    - run: python --version && docker --version
